language: node_js
node_js:
  - "12.14.0"
branches:
  only:
    - master
before_script:
  - npm install
jobs:
  include:
    - stage: Tests
    - script: echo Running Test
    - stage: Deploy
    - script: echo Running Deploy
