version: 2
jobs:
  tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - restore_cache:
          keys:
            - node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: test
          command: echo "all tsts to pass"
      - store_artifacts:
          path: coverage
  build:
    docker:
      - image: buildpack-deps:stable-scm
    steps:
      - checkout
      - run:
          command: ls
      - run:
          command: node -v

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - tests
      - hold:
          type: approval
          requires:
            - tests
