version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: node -v
            - run: npm -v
            - run: npm install
  deploy:
    working_directory: ~/repo
    docker:
      - image: docker:stable
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: node -v
workflows:
  build-and-test:
    jobs:
      - deploy:
