version: 2
jobs:
  tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - restore_cache:
          keys:
            - node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: test-react
          command: echo 1
      - store_artifacts:
          path: coverage



workflows:
  version: 2
  build-test-deploy:
    jobs:
      - tests
      - deploy-staging:
          requires:
            - tests
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - end-to-end-test
