version: 2
jobs:
  tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - restore_cache:
          keys:
            - node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: test
          command: echo "all tsts to pass"
      - store_artifacts:
          path: coverage
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: check-node
          command: node -v
      - run:
          name: install-npm
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: check
          command: ls -a
      - run:
          name: docker
          command: docker build -t a .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - tests
      - build:
          requires:
            - tests
      - hold:
          type: approval
          requires:
            - tests
            - build
